// Code generated by tygo. DO NOT EDIT.

//////////
// source: ingredient.go

export interface Ingredient {
  ID: string /* uuid */;
  Name: string;
  Kind?: string;
}

//////////
// source: recipe.go

export interface Recipe {
  id: string /* uuid */;
  title: string;
  description?: string;
  url?: string;
  ingredients: Ingredient[];
}
