// Code generated by tygo. DO NOT EDIT.
"import { model } from './internal/model"

//////////
// source: recipes.go

export type RecipeUseCases = any;
export interface CreateRecipeRequest {
  CreateRecipeDTO?: any /* usecases.CreateRecipeDTO */;
}

//////////
// source: recipes_reqres.go

export interface RecipeResponse extends model.Recipe {
}
