// Code generated by tygo. DO NOT EDIT.

//////////
// source: model.go

export interface Recipe {
  title: string;
  ingredients: {
    name: string;
    quantity: string;
    unit: string;
  }[];
  tags: string[];
  servings: number /* int */;
  steps: string[];
  description: string;
  headline: string;
}

//////////
// source: router.go

export interface CompleteRecipeRequest {
  url: string;
}
export interface CompleteRecipeResponse {
  recipe: Recipe;
}
